export enum MemberStatusEnum {
    CREATING = "CREATING",
    AVAILABLE = "AVAILABLE",
    CREATE_FAILED = "CREATE_FAILED",
    UPDATING = "UPDATING",
    DELETING = "DELETING",
    DELETED = "DELETED",
    INACCESSIBLE_ENCRYPTION_KEY ="INACCESSIBLE_ENCRYPTION_KEY",
}