export enum NodeStatusEnum {
    CREATING = "CREATING",
    AVAILABLE = "AVAILABLE",
    UNHEALTHY = "UNHEALTHY",
    CREATE_FAILED = "CREATE_FAILED",
    UPDATING = "UPDATING",
    DELETING = "DELETING",
    DELETED = "DELETED",
    FAILED = "FAILED",
    INACCESSIBLE_ENCRYPTION_KEY ="INACCESSIBLE_ENCRYPTION_KEY",
}