#!/bin/bash

infoln "Enrolling the CA admin"
mkdir -p organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/

export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/

set -x
fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-ORGANIZATION_NAME_PLACEHOLDER --tls.certfiles "${PWD}/organizations/fabric-ca/ORGANIZATION_NAME_PLACEHOLDER/ca-cert.pem"
{ set +x; } 2>/dev/null

echo 'NodeOUs:
Enable: true
ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-ORGANIZATION_NAME_PLACEHOLDER.pem
    OrganizationalUnitIdentifier: client
PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-ORGANIZATION_NAME_PLACEHOLDER.pem
    OrganizationalUnitIdentifier: peer
AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-ORGANIZATION_NAME_PLACEHOLDER.pem
    OrganizationalUnitIdentifier: admin
OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-ORGANIZATION_NAME_PLACEHOLDER.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/msp/config.yaml"

# Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

# Copy ORGANIZATION_NAME_PLACEHOLDER's CA cert to ORGANIZATION_NAME_PLACEHOLDER's /msp/tlscacerts directory (for use in the channel MSP definition)
mkdir -p "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/msp/tlscacerts"
cp "${PWD}/organizations/fabric-ca/ORGANIZATION_NAME_PLACEHOLDER/ca-cert.pem" "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/msp/tlscacerts/ca.crt"

# Copy ORGANIZATION_NAME_PLACEHOLDER's CA cert to ORGANIZATION_NAME_PLACEHOLDER's /tlsca directory (for use by clients)
mkdir -p "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/tlsca"
cp "${PWD}/organizations/fabric-ca/ORGANIZATION_NAME_PLACEHOLDER/ca-cert.pem" "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/tlsca/tlsca.ORGANIZATION_DOMAIN_PLACEHOLDER-cert.pem"

# Copy ORGANIZATION_NAME_PLACEHOLDER's CA cert to ORGANIZATION_NAME_PLACEHOLDER's /ca directory (for use by clients)
mkdir -p "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/ca"
cp "${PWD}/organizations/fabric-ca/ORGANIZATION_NAME_PLACEHOLDER/ca-cert.pem" "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/ca/ca.ORGANIZATION_DOMAIN_PLACEHOLDER-cert.pem"

infoln "Registering peer0"
set -x
fabric-ca-client register --caname ca-ORGANIZATION_NAME_PLACEHOLDER --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/ORGANIZATION_NAME_PLACEHOLDER/ca-cert.pem"
{ set +x; } 2>/dev/null

infoln "Registering user"
set -x
fabric-ca-client register --caname ca-ORGANIZATION_NAME_PLACEHOLDER --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/ORGANIZATION_NAME_PLACEHOLDER/ca-cert.pem"
{ set +x; } 2>/dev/null

infoln "Registering the org admin"
set -x
fabric-ca-client register --caname ca-ORGANIZATION_NAME_PLACEHOLDER --id.name ORGANIZATION_NAME_PLACEHOLDERadmin --id.secret ORGANIZATION_NAME_PLACEHOLDERadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ORGANIZATION_NAME_PLACEHOLDER/ca-cert.pem"
{ set +x; } 2>/dev/null

infoln "Generating the peer0 msp"
set -x
fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-ORGANIZATION_NAME_PLACEHOLDER -M "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/peers/peer0.ORGANIZATION_DOMAIN_PLACEHOLDER/msp" --csr.hosts peer0.ORGANIZATION_DOMAIN_PLACEHOLDER --tls.certfiles "${PWD}/organizations/fabric-ca/ORGANIZATION_NAME_PLACEHOLDER/ca-cert.pem"
{ set +x; } 2>/dev/null

cp "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/msp/config.yaml" "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/peers/peer0.ORGANIZATION_DOMAIN_PLACEHOLDER/msp/config.yaml"

infoln "Generating the peer0-tls certificates"
set -x
fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-ORGANIZATION_NAME_PLACEHOLDER -M "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/peers/peer0.ORGANIZATION_DOMAIN_PLACEHOLDER/tls" --enrollment.profile tls --csr.hosts peer0.ORGANIZATION_DOMAIN_PLACEHOLDER --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ORGANIZATION_NAME_PLACEHOLDER/ca-cert.pem"
{ set +x; } 2>/dev/null

# Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
cp "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/peers/peer0.ORGANIZATION_DOMAIN_PLACEHOLDER/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/peers/peer0.ORGANIZATION_DOMAIN_PLACEHOLDER/tls/ca.crt"
cp "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/peers/peer0.ORGANIZATION_DOMAIN_PLACEHOLDER/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/peers/peer0.ORGANIZATION_DOMAIN_PLACEHOLDER/tls/server.crt"
cp "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/peers/peer0.ORGANIZATION_DOMAIN_PLACEHOLDER/tls/keystore/"* "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/peers/peer0.ORGANIZATION_DOMAIN_PLACEHOLDER/tls/server.key"

infoln "Generating the user msp"
set -x
fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-ORGANIZATION_NAME_PLACEHOLDER -M "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/users/User1@ORGANIZATION_DOMAIN_PLACEHOLDER/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ORGANIZATION_NAME_PLACEHOLDER/ca-cert.pem"
{ set +x; } 2>/dev/null

cp "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/msp/config.yaml" "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/users/User1@ORGANIZATION_DOMAIN_PLACEHOLDER/msp/config.yaml"

infoln "Generating the org admin msp"
set -x
fabric-ca-client enroll -u https://ORGANIZATION_NAME_PLACEHOLDERadmin:ORGANIZATION_NAME_PLACEHOLDERadminpw@localhost:7054 --caname ca-ORGANIZATION_NAME_PLACEHOLDER -M "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/users/Admin@ORGANIZATION_DOMAIN_PLACEHOLDER/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ORGANIZATION_NAME_PLACEHOLDER/ca-cert.pem"
{ set +x; } 2>/dev/null

cp "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/msp/config.yaml" "${PWD}/organizations/peerOrganizations/ORGANIZATION_DOMAIN_PLACEHOLDER/users/Admin@ORGANIZATION_DOMAIN_PLACEHOLDER/msp/config.yaml"